### ISSUE TITLE
UI shows empty chart if there is no feedback

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#1211]
![Image](https://github.com/user-attachments/assets/b1e5311c-d232-44af-80b8-2689d8946b08)

```toml
[functions.generate_haiku2]
type = "chat"

[functions.generate_haiku2.variants.gpt_4o_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini"

[metrics.my_metric]
type = "boolean"
level = "episode"
optimize = "max"
```

I loaded the UI before sending any feedback.
