### ISSUE TITLE
Bad Error: wrong data type for `extra_body` in config

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#1440]
## Bad Config

```toml
[functions.bash_assistant]
type = "chat"

[functions.bash_assistant.variants.anthropic_claude_3_7_sonnet_20250219]
type = "chat_completion"
model = "anthropic::claude-3-7-sonnet-20250219"
max_tokens = 2048

[functions.bash_assistant.variants.anthropic_claude_3_7_sonnet_20250219.extra_body]
tools = [{ type = "bash_20250124", name = "bash" }]
thinking = { type = "enabled", budget_tokens = 1024 }
```

(Misformatted `extra_body`)

```python
from tensorzero import TensorZeroGateway


with TensorZeroGateway.build_embedded(
    config_file="config/tensorzero.toml",
) as t0:
    pass
```

## Current Error

```python
➜  tmp-anthropic-computer-use git:(main) ✗ uv run main.py
{"timestamp":"2025-03-20T18:40:34.299999Z","level":"ERROR","fields":{"message":"invalid type: map, expected a sequence\nin `functions.bash_assistant`\n"},"target":"tensorzero_internal::error"}                                            Traceback (most recent call last):
  File "/Users/gabrielbianconi/Developer/tensorzero/tmp-anthropic-computer-use/main.py", line 4, in <module>
    with TensorZeroGateway.build_embedded(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        config_file="config/tensorzero.toml",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as t0:
    ^
tensorzero.types.TensorZeroInternalError: TensorZeroInternalError: Failed to construct TensorZero client: ConfigParsing(Other { source: TensorZeroInternalError(Error(Config { message: "invalid type: map, expected a sequence\nin `functions.bash_assistant`\n" })) })
```

## Better Error

```
...
tensorzero.types.TensorZeroInternalError: Failed to construct TensorZero client: Bad configuration: invalid type: map, expected a sequence in `functions.bash_assistant.variants.anthropic_claude_3_7_sonnet_20250219.extra_body.`
```

It's really bad because the path in the error is incomplete (likely because of #335). We might need to kill the bounty and fix the upstream issue ourselves.

Less important but we should reduce the amount of boilerplate in the error (`ConfigParsing(Other { source: TensorZeroInternalError(Error(Config {  message: "xxx" }` → `Bad configuration: xxx`

## Fixed Config

```toml
[functions.bash_assistant]
type = "chat"

[functions.bash_assistant.variants.anthropic_claude_3_7_sonnet_20250219]
type = "chat_completion"
model = "anthropic::claude-3-7-sonnet-20250219"
max_tokens = 2048
extra_body = [
    { pointer = "/tools", value = [{ type = "bash_20250124", name = "bash" }] },
    { pointer = "/thinking", value = { type = "enabled", budget_tokens = 1024 } },
]
```
