### ISSUE TITLE
Decide on a Rust version policy

### ISSUE THREAD

**Issue by Aaron1011** [tensorzero/tensorzero#1941]
Currently, we use `rust:latest` Docker images in several places, but we also end up building/testing against slightly older Rust versions on Namespace builders. As a result, code which needs the current latest Rust version will fail to pass CI: https://github.com/tensorzero/tensorzero/pull/1940

We should decide what our minimum supported Rust version (MSRV) should be, and document this. This will become more important when we release the Rust client - right now, this only affects users who build the gateway from source instead of using our Docker images.

**Comment by GabrielBianconi** [comment]
You can pick!

**Comment by nyurik** [comment]
`cargo msrv find --write-msrv` usually works well :)

**Comment by nyurik** [comment]
P.S.  For CI, you can use these steps:

```yaml
- name: Get MSRV package metadata
  id: metadata
  run: cargo metadata --no-deps --format-version 1 | jq -r '"msrv=" + .packages[0].rust_version' >> $GITHUB_OUTPUT
  
- name: Install rust (${{ steps.metadata.outputs.msrv }})
  uses: dtolnay/rust-toolchain@master
  with:
    toolchain: ${{ steps.metadata.outputs.msrv }}
  
- uses: Swatinem/rust-cache@v2
```
