### ISSUE TITLE
Display gateway errors in the SFT job page

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#2037]
When you specify a path that doesn't yet exist, we get:

```
TensorZeroInternalError: Failed to construct TensorZero client: ConfigParsing(Other { source: TensorZeroInternalError(Error(Config { message: "Failed to create filesystem object store for path: object_storage: Generic LocalFileSystem
error: Unable to canonicalize filesystem root: object_storage" })) })
```

from

```toml
[object_storage]
type = "filesystem"
path = "object_storage"  # does not exist yet
```

We should either create the path ourselves or give a clearer error.
