### ISSUE TITLE
Add an optional `name` field to `tools` in the config

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#230]
Currently, given `tools.tool_name` we use `tool_name` as the name given to the model. However, this value must be globally unique, and we might want the same name for different tools.

Let's add an optional `name` field to this table. If missing, the behavior stays as is. If provided, that overrides the function name provided to the model.

**Comment by hk1997** [comment]
@GabrielBianconi Can I work on this issue?

**Comment by GabrielBianconi** [comment]
Sounds good, thanks @hk1997!

**Comment by hk1997** [comment]
@GabrielBianconi In your original description of the issue, you are talking about a table, what is this table?

Further, I'm trying to visualize how would the toml config look like for tools after this change? And what is the actual benefit of this feature request in tensorzero?

**Comment by GabrielBianconi** [comment]
@hk1997 A TOML table in the config: https://toml.io/en/v1.0.0#table

Right now we have, say:

```toml
[tools.get_temperature]
description = "Get the current temperature for a given location."
parameters = "tools/get_temperature.json"
```

But what if we wanted two tools with different parameters/description but same name? We can't today because the `tools.get_temperature` ID has to be unique. So we want:

```toml
[tools.get_temperature_A]
name = "get_temperature"
description = "Get the current temperature for a given location."
parameters = "tools/get_temperature_A.json"

[tools.get_temperature_B]
name = "get_temperature"
description = "Get the current temperature for a given location."
parameters = "tools/get_temperature_B.json"
```

This would send the tool name as `get_temperature` to the model. The behavior should be that if the `name` is provided, use that; otherwise default to the ID.

If the user tries to send two tools with the same name to the model, error.
