### ISSUE TITLE
Support a path prefix (base path) in the gateway

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#2598]
We should allow users to configure a path prefix for endpoints.

For the gateway, the user might do:

```toml
[gateway]
base_path = '/xyz'  # defaults to '/' i.e. no prefix
```

If the user does that, then the gateway exposes `/xyz/inference`, `/xyz/feedback`, etc.

We need to make sure clients support this change. When configuring an HTTP client (or other like the UI), the user should specify `gateway_url="scheme://host:port/xyz"`.
