### ISSUE TITLE
Error paths are misleading for children of enums in `tensorzero.toml` config (upstream crate bug)

### ISSUE THREAD

**Issue by virajmehta** [tensorzero/tensorzero#335]
Downstream of dtolnay/path-to-error#1.

---

**Minimal Example**

```toml
[functions.my_function]
type = "chat"

[functions.my_function.variants.my_variant]
# The following entry is mandatory but it's missing
# type = "chat_completion"
model = "anthropic::claude-3-haiku-20240307"

[gateway]
disable_observability = true
```

Right now this gives:

```
"missing field `type`\nin `functions.my_function`\n"
```

We want:

```
"missing field `type`\nin `functions.my_function.variants.my_variant`\n"
```

---

**Another Example**

We get...

```
 "Failed to load config: missing field `type`\nin `functions.play_chess_pgn`"
```

... for an error for the following TOML:

```toml
[functions.play_chess_pgn]
type = "json"
user_schema = "functions/play_chess_pgn/user_schema.json"
output_schema = "functions/play_chess_pgn/output_schema.json"

[functions.play_chess_pgn.variants.claude-3.5-sonnet]
weight = 1
type = "chat_completion"
model = "claude-3.5-sonnet-20240620"
system_template = "functions/play_chess_pgn/chess_prompt/system_template.minijinja"
user_template = "functions/play_chess_pgn/chess_prompt/user_template.minijinja"
```

despite the error being in the escaping of the name "claude-3.5-sonnet".

**Comment by GabrielBianconi** [comment]
We'll pay a $500 bounty to whoever solves the upstream issue (dtolnay/path-to-error#1).

The passing criteria is a new `serde_path_to_error` release that solves our downstream issue (tensorzero/tensorzero#335).

**Comment by Cabbache** [comment]
@GabrielBianconi Does [this](https://github.com/tensorzero/tensorzero/compare/main...Cabbache:tensorzero:main) work for you?

For @virajmehta 's config:
```
"Failed to load config: missing field `type`\nin `functions.play_chess_pgn`\n @ functions.play_chess_pgn.variants.claude-3.5-sonnet.weight"
```

**Comment by GabrielBianconi** [comment]
Hi @Cabbache - I don't think that's correct, it's flagging `weight` but that's also not where the error is.

Here's a minimal example:

```toml
[functions.my_function]
type = "chat"

[functions.my_function.variants.my_variant]
# The following entry is mandatory but it's missing
# type = "chat_completion"
model = "anthropic::claude-3-haiku-20240307"

[gateway]
disable_observability = true
```

Right now this gives `"missing field `type`\nin `functions.my_function`\n"`.

We want `"missing field `type`\nin `functions.my_function.variants.my_variant`\n".
