### ISSUE TITLE
Implement configurable retries for variants

### ISSUE THREAD

**Issue by virajmehta** [tensorzero/tensorzero#357]

**Comment by virajmehta** [comment]
Current best idea for a design:

have chat completion, evaluator, dicl variants all contain a retries = {"n" = 3} style block (default 1) and do retries around model requests, i.e. for a block that looks like 

```toml
[models.gpt-4o]
# ...
routing = ["openai", "azure"]
# ...

[models.gpt-4o.providers.openai]
# ...

[models.gpt-4o.providers.azure]
# ...
```

we would do retries = {"n" = 3} in the variant and then the variant inference would look like 
OpenAI -> Azure -> wait -> OpenAI -> Azure -> wait -> OpenAI -> Azure -> next variant
