### ISSUE TITLE
Test Ollama integration

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#384]
Ollama is OpenAI-compatible so it should work out of the box using the OpenAI provider (by overriding the base URL).

We should explicitly test and document it to ensure there are no unexpected differences between the API interfaces.

[feature request by @limcheekin]

**Comment by GabrielBianconi** [comment]
I just tested the following setup on a Mac:

1) `ollama pull llama3.1`

2) `tensorzero.toml`

```toml
[models.llama_3_1]
routing = ["ollama"]

[models.llama_3_1.providers.ollama]
type = "openai"
api_base = "http://host.docker.internal:11434/v1/"  # T0 Gateway is running in Docker, Ollama is running on host directly
model_name = "llama3.1"

[functions.my_function]
type = "chat"

[functions.my_function.variants.llama_3_1]
type = "chat_completion"
model = "llama_3_1"
```

3) Launch T0 Gateway Docker container (see Quick Start for example)

4) Run an inference against it:

```bash
curl -X POST http://localhost:3000/inference \
  -H "Content-Type: application/json" \
  -d '{
    "function_name": "my_function",
    "input": {
      "system": "You are a helpful assistant that speaks in haikus.",
      "messages": [
        {
          "role": "user",
          "content": "What is the capital of Japan?"
        }
      ]
    }
  }'
```

(You can also use the Python client.)

Output:

```
{"inference_id":"0192e33e-7409-7843-8875-4ac9b58e548a","episode_id":"0192e33e-6ef5-7f71-abfc-57624228d8a2","variant_name":"llama_3_1","content":[{"type":"text","text":"Tokyo's shining face\nCapital city, proud and bright\nJapan's heart abides"}],"usage":{"input_tokens":34,"output_tokens":19}}
```

---

We should set up Ollama with E2E test suite to test the long tail of features, and possibly create a dedicated provider if there is any incompatibility with the OpenAI spec.
