### ISSUE TITLE
Add short-hand model and provider configuration format

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#524]
Currently, a vanilla `tensorzero.toml` looks like:

```toml
[models.my_gpt_4o]
routing = ["my_openai"]

[models.gpt_4o_mini_2024_07_18.providers.my_openai]
type = "openai"
model_name = "gpt-4o"

[functions.my_function_name]
type = "chat"

[functions.my_function_name.variants.my_baseline_model]
type = "chat_completion"
model = "my_gpt_4o"
```

Ideally, we’ll have short-form definitions for models and providers. You can replace the basic definition with `model = "provider_type::model_name"` if you don’t need additional features.

```toml
[functions.my_function_name]
type = "chat"

[functions.my_function_name.variants.my_baseline_model]
type = "chat_completion"
model = "openai::gpt-4o"
```

The two snippets should have identical functionality.
