### ISSUE TITLE
Allow clients to submit inference parameters that aren't explicitly supported

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#566]
If a user wants to benefit from a long-tail inference parameter we don't support, we should let them provide this information at inference time.

One option is to provide an "overwrite" JSON object. This object might need to be linked to specific variants (like inference params). We need to consider how to deal with those for advanced variant types.

**Comment by virajmehta** [comment]
@GabrielBianconi my conception of this is that you can do this at config time too by something like this:

```toml
[functions.basic_test.variants.fireworks]
type = "chat_completion"
model = "llama3.1-8b-instruct-fireworks"
system_template = "../../fixtures/config/functions/basic_test/prompt/system_template.minijinja"
max_tokens = 100
additional_inference_parameters = { "response_format" = {"type": "grammar", "grammar": diagnosis_grammar}}
```
for e.g. Fireworks grammar mode. Obviously this has issues in that it conflicts with JSON functions so I'm not convinced this is the correct way to do so. But I think we need some way to override at config time too.
