### ISSUE TITLE
Short-hand model configuration doesn't work if there aren't any models explicitly defined

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#603]
The following `tensorzero.toml`...

```toml
[functions.chatbot]
type = "chat"

[functions.chatbot.variants.openai]
type = "chat_completion"
model = "openai::gpt-4o-mini-2024-07-18"
```

...leads to:

```
gateway-1  | {"timestamp":"2024-12-26T04:46:24.615350Z","level":"ERROR","message":"missing field `models`\n","spans":[{"name":"load"}]}
gateway-1  | {"timestamp":"2024-12-26T04:46:24.615395Z","level":"ERROR","message":"Failed to load config: missing field `models`\n"}
```

The following `tensorzero.toml` works.

```toml
[models.not_used]
routing = ["openai"]

[models.not_used.providers.openai]
type = "openai"
model_name = "not_used"

[functions.chatbot]
type = "chat"

[functions.chatbot.variants.openai]
type = "chat_completion"
model = "openai::gpt-4o-mini-2024-07-18"
```
