### ISSUE TITLE
Adjust AWS Bedrock to require explicit opt-in for region detection behavior

### ISSUE THREAD

**Issue by Aaron1011** [tensorzero/tensorzero#856]
When we construct an `AWSBedrockProvider` (during config parsing), we currently use the full AWS `RegionProviderchain` logic when the region is not explicitly specified in the config file:

https://github.com/tensorzero/tensorzero/blob/84f95d9491c83638c42baecfe8ccf7d739aca8e8/tensorzero_internal/src/inference/providers/aws_bedrock.rs#L51-L65

The AWS code tries several different strategies to find the current region, including making network requests to `169.254.169.254` (the [Instance Metadata Service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html).
When not running on AWS, this can take several seconds to complete, which delays gateway startup in an unusual place (config parsing). 

I think we should adjust the provider as follows:
1. By default, require the Bedrock `region` field to be explicitly specified in the `config.toml`, and produce a parse error if it's not set.
2. Add a boolean config option called `auto_detect_region` to the Bedrock provider config. This defaults to `false` - when enabled, it uses the `RegionProviderChain` to try and auto-detect a region. Alternatively, we allow `region = "auto-detect"` (assuming that this will never be a valid AWS region).

Example valid configs after this change:

```toml
[models.claude-3-haiku-20240307-aws-bedrock.providers.aws-bedrock]
type = "aws_bedrock"
model_id = "anthropic.claude-3-haiku-20240307-v1:0"
region = "us-east-1"
```

```toml
[models.claude-3-haiku-20240307-aws-bedrock.providers.aws-bedrock]
type = "aws_bedrock"
model_id = "anthropic.claude-3-haiku-20240307-v1:0"
auto_detect_region = true
```
