### ISSUE TITLE
Support `extra_body` for variant configuration

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#910]
Add an optional field `extra_body` to the variant configuration block:

* `chat_completion`: yes
* `experimental_xxx_of_n`: inside the `evaluator` (candidates will get it via their own variant types)
* `experimental_dynamic_in_context_learning `:  yes (applies to chat generation call not embedding call)

If provided, this field will update/overwrite the request body to LLM APIs with the entries in this object.

**Example**

```toml
[functions.my_function.variants.my_variant]
type = "chat_completion"
model = "my_model"
extra_body = { "a" = "1", "b" = { "c" = 2} }
```

Overwrites the body of LLM API calls with the following:

```js
{
  "a": "1",
  "b": {
     "c": 2
  },
  // default fields 
}
```
