### ISSUE TITLE
Support `extra_body` for model provider configuration

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#911]
Add an optional field `extra_body` to the model provider configuration block:

If provided, this field will update/overwrite the request body to LLM APIs with the entries in this object.

**Example**

```toml
[models.my_model.provider.my_provider]
# ...
extra_body = { "a" = "1", "b" = { "c" = 2} }
```

Overwrites the body of LLM API calls with the following:

```js
{
  "a": "1",
  "b": {
     "c": 2
  },
  // default fields 
}
```
